name: screenshot_callback
description: Flutter plugin that allows you to detect mobile screenshot and execute callback functions on iOS and Android.
version: 1.1.5
homepage: https://github.com/flutter-moum/flutter_screenshot_callback

environment:
  sdk: ">=2.15.0 <=3.0.3"
  flutter: ">=3.10.4"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.flutter.moum.screenshot_callback
        pluginClass: ScreenshotCallbackPlugin
      ios:
        pluginClass: ScreenshotCallbackPlugin
